---
- name: Initial Prep after a reset
  hosts: all
  gather_facts: false
  become: false

  tasks:
    -  ansible.windows.win_domain_membership:
        dns_domain_name: '{{ domain_name }}'
        domain_admin_user: '{{ pass1_user }}'
        domain_admin_password: '{{ pass1_pwd }}'
        state: domain
       register: domain_state

    -  ansible.windows.win_reboot:
        when: domain_state.reboot_required